# Generated by Django 3.0.5 on 2020-06-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200604_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_demo_user',
            field=models.BooleanField(default=False),
        ),
    ]
