"""Settings for the local instance of our django app.  WARNING: this file should
not be committed or shared with others.
"""

# To set your local settings, edit the values below and change the name of this
# file to 'local_settings.py'

# A secret key can be generated by opening a django shell and running the
# get_secret_key() function. Copy and past it in below.
# python manage.py shell
# from django.core.management.utils import get_random_secret_key
# get_random_secret_key()
SECRET_KEY = "add a secret key here"

# Debug should be set to False for production environments, True for dev
# environments.
DEBUG = True

# This can be blank if debug it True else it should contain the names of the
# appropriate servers.
ALLOWED_HOSTS = []
