# Generated by Django 3.0.5 on 2020-05-08 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('priority_level', models.IntegerField(choices=[(3, 'Low'), (6, 'Medium'), (9, 'High')], default=3)),
                ('estimated_duration', models.DurationField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_due', models.DateField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('date_completed', models.DateField(blank=True)),
                ('assigned_to_project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='projects.Project')),
                ('assigned_to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
