# Generated by Django 3.0.5 on 2020-05-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200511_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_due',
            field=models.DateField(help_text='dd/mm/yyyy'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_duration',
            field=models.DurationField(help_text='hh:mm'),
        ),
    ]
