# Generated by Django 3.0.5 on 2020-05-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomment',
            name='text',
            field=models.TextField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='text',
            field=models.TextField(verbose_name='comment'),
        ),
    ]
