# Generated by Django 3.0.5 on 2020-05-08 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modifed', models.DateTimeField(auto_now=True, verbose_name='Date and time project was last modifed')),
                ('date_due', models.DateField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('date_completed', models.DateField(blank=True)),
                ('team', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
