# Generated by Django 3.0.5 on 2020-05-29 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200529_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_modifed',
            new_name='date_modified',
        ),
    ]
